name: CI Build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean verify