
services:

  app:
    container_name: app
    build:
      context: .
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: "default"
    ports:
      - "80:80"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.7.1
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - app

  grafana:
    container_name: grafana
    image: grafana/grafana:12.2.1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin #⚠️ DO NOT USE IN PRODUCTION
      - GF_SECURITY_ADMIN_PASSWORD=admin #⚠️ DO NOT USE IN PRODUCTION
    volumes:
      - ./docker/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./docker/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/dashboards:/var/lib/grafana/dashboards
