ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER TEST_SCHEMA IDENTIFIED BY Ag101Pwd123;
GRANT CREATE SESSION TO TEST_SCHEMA;
GRANT CONNECT, RESOURCE TO TEST_SCHEMA;
ALTER USER TEST_SCHEMA QUOTA UNLIMITED ON USERS;