ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER developer IDENTIFIED BY developer;

GRANT CONNECT, RESOURCE TO developer;
GRANT CREATE SESSION TO developer;
GRANT CREATE TABLE TO developer;
GRANT CREATE SEQUENCE TO developer;
GRANT CREATE PROCEDURE TO developer;
GRANT CREATE VIEW TO developer;
GRANT CREATE TRIGGER TO developer;

GRANT DROP ANY TABLE TO developer;
GRANT DROP ANY PROCEDURE TO developer;
GRANT DROP ANY SEQUENCE TO developer;
GRANT DROP ANY VIEW TO developer;

GRANT SELECT ANY TABLE TO developer;
GRANT INSERT ANY TABLE TO developer;
GRANT UPDATE ANY TABLE TO developer;
GRANT DELETE ANY TABLE TO developer;

ALTER USER developer QUOTA UNLIMITED ON USERS;

COMMIT;
