server:
  port: 8083

spring:

  application:
    name: spring-keycloak-example-default

logging:

  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss} | ${spring.application.name} | %class{30} | %level | %m%n"