server:
  port: ${SERVER_PORT:8083}

spring:

  application:
    name: spring-keycloak-example-OIDC

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${AUTH_CLIENT_ID:oidc-client}
            client-secret: ${AUTH_CLIENT_SECRET:pvRQkTKcE2zZw9vxT30oXC1Zynq2b3yw}
            scope: ${AUTH_SCOPE:openid, profile, email}
            authorization-grant-type: ${AUTH_GRANT_TYPE:authorization_code}
            redirect-uri: ${AUTH_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
        provider:
          keycloak:
            issuer-uri: ${AUTH_ISSUER_URI:http://localhost:8080/realms/redirect-login-example}

logging:

  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss} | ${spring.application.name} | %class{30} | %level | %m%n"