spring:
  application:
    name: spring-oracle-example-dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521}
    username: ${SPRING_DATASOURCE_USERNAME:developer}
    password: ${SPRING_DATASOURCE_PASSWORD:developer}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:oracle.jdbc.OracleDriver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_HIBERNATE_DIALECT:org.hibernate.dialect.OracleDialect}
