
services:

  app-postgres:
    build:
      context: .
    ports:
      - "8081:8081"

  postgres:
    image: postgres:17
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: user123
