server:
  port: 8082

spring:

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console

  batch:
    initialize-schema: always
    job:
      enabled: false
    batch-size: 1000
