
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: "OIDC"
      AUTH_CLIENT_ID: oidc-client
      AUTH_CLIENT_SECRET: pvRQkTKcE2zZw9vxT30oXC1Zynq2b3yw
      AUTH_SCOPE: openid, profile, email
      AUTH_GRANT_TYPE: authorization_code
      AUTH_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"
      AUTH_ISSUER_URI: http://localhost:8080/realms/redirect-login-example
    ports:
      - "8083:8083"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - spring_keycloak

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/oidc_auth_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin #⚠️ DO NOT USE IN PRODUCTION
      KEYCLOAK_ADMIN_PASSWORD: admin #⚠️ DO NOT USE IN PRODUCTION
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
    volumes:
      - ./docker/keycloak/certs:/opt/keycloak/certs
    depends_on:
      - keycloak-database
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - spring_keycloak

  keycloak-database:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: postgres #⚠️ DO NOT USE IN PRODUCTION
      POSTGRES_PASSWORD: password #⚠️ DO NOT USE IN PRODUCTION
    ports:
      - "5432:5432"
    volumes:
      - ./docker/keycloak/backups/oidc_auth_db_backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring_keycloak

networks:
  spring_keycloak: