
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 80
      SPRING_PROFILES_ACTIVE: "default"
    ports:
      - "80:80"
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: dev-file
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin #⚠️ DO NOT USE IN PRODUCTION
      KEYCLOAK_ADMIN_PASSWORD: admin #⚠️ DO NOT USE IN PRODUCTION
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
    volumes:
      - ./docker/keycloak:/opt/keycloak/certs