
services:

  #Not usable
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8083
      SPRING_PROFILES_ACTIVE: "OIDC"
      AUTH_CLIENT_ID: oidc-client
      AUTH_CLIENT_SECRET: pvRQkTKcE2zZw9vxT30oXC1Zynq2b3yw
      AUTH_SCOPE: openid, profile, email
      AUTH_GRANT_TYPE: authorization_code
      AUTH_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"
      AUTH_ISSUER_URI: http://localhost:8080/realms/redirect-login-example
    ports:
      - "8083:8083"
    depends_on:
      - keycloak
      - keycloak-database
    networks:
      - spring_keycloak

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/oidc_auth_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8080"
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: admin #⚠️ DO NOT USE IN PRODUCTION
      KEYCLOAK_ADMIN_PASSWORD: admin #⚠️ DO NOT USE IN PRODUCTION
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
    volumes:
      - ./docker/keycloak/certs:/opt/keycloak/certs
    depends_on:
      - keycloak-database
    networks:
      - spring_keycloak


  keycloak-database:
    image: postgres:14.18-alpine3.22
    container_name: keycloak-database
    environment:
      POSTGRES_USER: postgres #⚠️ DO NOT USE IN PRODUCTION
      POSTGRES_PASSWORD: password #⚠️ DO NOT USE IN PRODUCTION
    ports:
      - "5432:5432"
    volumes:
      - ./docker/keycloak/backups/oidc_auth_db_backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring_keycloak

networks:
  spring_keycloak: